### ISSUE TITLE
Feature Suggestion: Side arrows to navigate through open files

### ISSUE THREAD

**Issue by vvks** [demonmhon/brackets-working-file-tabs#2]
Firstly, thanks for the extension.

But, when you open a lot of files, they tend to appear below existing row of opened files. This way, if you have a lot of files open, you have 3 rows of tabs for your opened files.

It would be better if all the opened files aligned in one single row and you could use arrows to on both side to view the opened files

**Comment by demonmhon** [comment]
Implemented in v1.0.2
